name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.4
            otp: 18
          - elixir: 1.5
            otp: 18
          - elixir: 1.6
            otp: 19
          - elixir: 1.7
            otp: 19
          - elixir: 1.8
            otp: 20
          - elixir: 1.9
            otp: 20
          - elixir: 1.10
            otp: 21
          - elixir: 1.11
            otp: 22
          - elixir: 1.11
            otp: 23
            warnings_as_errors: true
            static_analysis: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.hex
            ~/.mix
            _build
          key: ${{ matrix.otp }}-${{ matrix.elixir }}-build
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
      - run: mix test
      - run: mix dialyzer --halt-exit-status
        if: matrix.static_analysis
